app = "yt-transcriber"
primary_region = "iad"

[build]

[env]
  PORT = "3001"
  YTDLP_PATH = "yt-dlp"
  FFMPEG_PATH = "ffmpeg"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
