services:
  - type: web
    name: yt-transcriber
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip ffmpeg
      python3 -m pip install --user yt-dlp
      echo 'export PATH="/root/.local/bin:$PATH"' >> ~/.bashrc
      ln -sf /root/.local/bin/yt-dlp /usr/local/bin/yt-dlp
      npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: YTDLP_PATH
        value: yt-dlp
      - key: FFMPEG_PATH
        value: ffmpeg
